import os
from flask import Blueprint, render_template, Response, request, jsonify

ml_bp = Blueprint('ml', __name__)


def is_vercel_runtime():
    return bool(os.getenv('VERCEL'))


def get_ml_engine():
    if is_vercel_runtime():
        return None, RuntimeError('ML camera engine is disabled on Vercel serverless')
    try:
        from .. import ml_engine
        return ml_engine, None
    except Exception as exc:
        return None, exc

@ml_bp.route('/')
def index():
    # Allow overriding ML backend with an external service via ML_BACKEND_URL
    ml_backend_url = os.getenv('ML_BACKEND_URL', '') or ''
    ml_backend_url = ml_backend_url.rstrip('/')
    available = bool(ml_backend_url) or not is_vercel_runtime()
    return render_template(
        'ml/index.html',
        ml_camera_backend_available=available,
        ml_backend_url=ml_backend_url
    )

# streaming route serves MJPEG frames generated by ml_engine
@ml_bp.route('/stream')
def stream():
    ml_engine, error = get_ml_engine()
    if ml_engine is None:
        return jsonify({
            'error': 'ML camera engine is unavailable on this deployment',
            'detail': str(error),
            'available': False
        }), 200
    return Response(ml_engine.gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

@ml_bp.route('/camera/toggle', methods=['POST'])
def camera_toggle():
    try:
        ml_engine, error = get_ml_engine()
        if ml_engine is None:
            return jsonify({
                'enabled': False,
                'available': False,
                'detail': str(error)
            })
        # support explicit enable/disable via JSON body: {"enabled": true/false}
        data = request.get_json(silent=True) or {}
        if 'enabled' in data:
            if bool(data['enabled']):
                ml_engine.enable_capture()
            else:
                ml_engine.disable_capture()
            return jsonify({'enabled': ml_engine.is_capture_enabled()})

        # fallback: toggle when no explicit flag provided (legacy behavior)
        enabled = ml_engine.toggle_capture()
        return jsonify({'enabled': bool(enabled)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@ml_bp.route('/camera/status')
def camera_status():
    try:
        ml_engine, error = get_ml_engine()
        if ml_engine is None:
            return jsonify({'enabled': False, 'available': False, 'detail': str(error)})
        return jsonify({'enabled': ml_engine.is_capture_enabled()})
    except Exception as e:
        return jsonify({'error': str(e)}), 500
